### ISSUE TITLE
[BUG] Remote addons falsely marked as installed if "unzip" is not installed.

### ISSUE THREAD

**Issue by zlewe** [qcr/benchbot_addons#1]
https://github.com/qcr/benchbot_addons/blob/80f636608890e561fff917aa93b11a65dc6c5a1c/benchbot_addons/manager.py#L254

If the system doesn't have unzip installed, the zip will not be extracted. However, the state of the addon will still be recorded as installed.

Potential solution:
- return code checks

**Comment by btalb** [comment]
Thanks for a really useful bug report @zlewe .

We'll hopefully get an update out tomorrow that fixes that.

In the meantime, removing the `benchbot/addons/benchbot_addons/.state` file and running the installer again with `unzip` installed should work.
